<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>desktop-helper</AssemblyName>
    <RootNamespace>DesktopHelper</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="desktop-uia-helper.cs" />
    <None Include="desktop-uia-helper.cs" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.14" />
  </ItemGroup>
</Project>
